spring:
  application:
    name: bankApi
  datasource:
    url: jdbc:h2:~/bankApi
    username: bankApi
    password: bankApi
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true