spring:
  application:
    name: bankApi
  datasource:
    url: jdbc:h2:~/bankApi
    username: bankApi
    password: bankApi
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true